//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHCT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\Char.mdb")]
        public string CharConnectionString {
            get {
                return ((string)(this["CharConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool b_HighLightFontChar {
            get {
                return ((bool)(this["b_HighLightFontChar"]));
            }
            set {
                this["b_HighLightFontChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool b_OutputAllPages {
            get {
                return ((bool)(this["b_OutputAllPages"]));
            }
            set {
                this["b_OutputAllPages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool b_OutputSeparate {
            get {
                return ((bool)(this["b_OutputSeparate"]));
            }
            set {
                this["b_OutputSeparate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool b_OutputFontSupported {
            get {
                return ((bool)(this["b_OutputFontSupported"]));
            }
            set {
                this["b_OutputFontSupported"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string s_OutputSeparate {
            get {
                return ((string)(this["s_OutputSeparate"]));
            }
            set {
                this["s_OutputSeparate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新細明體")]
        public string s_FontDefaultA {
            get {
                return ((string)(this["s_FontDefaultA"]));
            }
            set {
                this["s_FontDefaultA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HanaMinB")]
        public string s_FontDefaultB {
            get {
                return ((string)(this["s_FontDefaultB"]));
            }
            set {
                this["s_FontDefaultB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新細明體")]
        public string s_ComboRegularFont {
            get {
                return ((string)(this["s_ComboRegularFont"]));
            }
            set {
                this["s_ComboRegularFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新細明體")]
        public string s_ComboCharBlockFont {
            get {
                return ((string)(this["s_ComboCharBlockFont"]));
            }
            set {
                this["s_ComboCharBlockFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新細明體")]
        public string s_ComboFilterFont {
            get {
                return ((string)(this["s_ComboFilterFont"]));
            }
            set {
                this["s_ComboFilterFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新細明體")]
        public string s_ComboFilterBtnFont {
            get {
                return ((string)(this["s_ComboFilterBtnFont"]));
            }
            set {
                this["s_ComboFilterBtnFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("新細明體")]
        public string s_ComboPartFont {
            get {
                return ((string)(this["s_ComboPartFont"]));
            }
            set {
                this["s_ComboPartFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("無")]
        public string s_Phoenics1 {
            get {
                return ((string)(this["s_Phoenics1"]));
            }
            set {
                this["s_Phoenics1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("無")]
        public string s_Phoenics2 {
            get {
                return ((string)(this["s_Phoenics2"]));
            }
            set {
                this["s_Phoenics2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("無")]
        public string s_Phoenics3 {
            get {
                return ((string)(this["s_Phoenics3"]));
            }
            set {
                this["s_Phoenics3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lavender")]
        public string s_PhoenicsBG1 {
            get {
                return ((string)(this["s_PhoenicsBG1"]));
            }
            set {
                this["s_PhoenicsBG1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightCyan")]
        public string s_PhoenicsBG2 {
            get {
                return ((string)(this["s_PhoenicsBG2"]));
            }
            set {
                this["s_PhoenicsBG2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PapayaWhip")]
        public string s_PhoenicsBG3 {
            get {
                return ((string)(this["s_PhoenicsBG3"]));
            }
            set {
                this["s_PhoenicsBG3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int i_SearchHistory {
            get {
                return ((int)(this["i_SearchHistory"]));
            }
            set {
                this["i_SearchHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int i_FontSizeFilterTitle {
            get {
                return ((int)(this["i_FontSizeFilterTitle"]));
            }
            set {
                this["i_FontSizeFilterTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int i_FontSizeFilterCharBtn {
            get {
                return ((int)(this["i_FontSizeFilterCharBtn"]));
            }
            set {
                this["i_FontSizeFilterCharBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int i_FontSizeFilterClrBtn {
            get {
                return ((int)(this["i_FontSizeFilterClrBtn"]));
            }
            set {
                this["i_FontSizeFilterClrBtn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int i_FontSizeCharBlock {
            get {
                return ((int)(this["i_FontSizeCharBlock"]));
            }
            set {
                this["i_FontSizeCharBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int i_FontSizeOutput {
            get {
                return ((int)(this["i_FontSizeOutput"]));
            }
            set {
                this["i_FontSizeOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool b_DebugMode {
            get {
                return ((bool)(this["b_DebugMode"]));
            }
            set {
                this["b_DebugMode"] = value;
            }
        }
    }
}
